spring:
  application:
    name: SwiftCodeAPI
  datasource:
    username: root
    password: "!_SuperSecureDB_!"
    url: jdbc:mysql://localhost:3306/swiftcodes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
