spring:
  application:
    name: SwiftCodeAPI
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      initialization-fail-timeout: 10000
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
